# Generated by Django 4.1.5 on 2023-01-24 19:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_usuario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 24, 19, 29, 12, 143108, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
